server:
  port: ${PORT:9003}
spring:
  application:
    name: supergo-monitor
  security:
    user:
      name: "jackhu"
      password: "123456"
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:10086/eureka}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    metadata-map:
      user.name: "jackhu"
      user.password: "123456"
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"