spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update