server:
  port: 8081
  servlet:
    context-path: /provider


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

  instance:
    instance-id: hcl-provider-test
#    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
#    prefer-ip-address: true

spring:
  application:
    name: hcl-provider-8081

  jpa:
    # 指定是否在spring容器启动时创建表，默认为false
    generate-ddl: false
    # 是否在控制台打印sql语句，默认false
    show-sql: true
    # 指定重启时不重新更新表
    hibernate:
      ddl-auto: none
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    # 指定spring.jpa.show-sql为true时，是否显示动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 指定spring.jpa.show-sql为true时，是否显示查询语句的查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

