spring:
  application:
    name: lock-demo
  datasource:
    url: jdbc:mysql://localhost:3306/supergo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  redis:
    port: 6379
    host: 192.168.66.66
server:
  port: 9990
mapper:
  not-empty: false
